<style>

.sectorcasesToday td{
    padding-right: 10px;
    padding-left: 10px;
    padding-top: 10px;
    padding-bottom: 10px;
    font-size: 25px;
}
table.BS, .BS th {
    border: 1px solid black;
    border-collapse: collapse;
    font-size: 16px;
    text-align: center;
}
.BS td{
    border: 1px solid black;
    border-collapse: collapse;

    text-align: center;
}


</style>

<div class="container-fluid">
	<div class="row">

        <div class="col-md-6 mt-3">
            <div class="col-md-14">
                <h2 class="title">New Cases Today By Sector</span></h2>
                <div class="row row_data" style="height:500px; padding-right:50px;">

                    <div class="col-md-12">
                                        <div class="card card-blue-white mt-0">
                                        <div class="card-body p-0">
                                        <div>
                                            <table style="width:100%;" class="sectorcasesToday BS">
                                            <tr style="background-color:rgba(255,255,255,0.1); color:#fff;"><th>Sector</th><th>Number of Cases</th><th>Total Value of Cases</th></tr>

                                            </table>
                                        </div>
                                    </div>
                                </div>
                    </div>
                </div>
            </div>


        </div>
        <div class="col-md-6 mt-3">
            <div class="col-md-14">
                <h2 class="title">New Cases Today By Client</span></h2>
                <div class="row row_data" style="height:500px; padding-right:50px;">

                    <div class="col-md-12">
                                        <div class="card card-blue-white mt-0">
                                        <div class="card-body p-0">
                                        <div>
                                            <table style="width:100%;" class="casesToday BS">
                                            <tr style="background-color: rgba(255,255,255,0.1); color:#fff;"><th>Client</th><th>Number of Cases</th><th>Total Value of Cases</th></tr>

                                            </table>
                                        </div>
                                    </div>
                                </div>
                    </div>
                </div>
            </div>


        </div>


    </div>
</div>



<script>
if (!result_complete_sort_cases) {
	var result_complete_sort_cases=0;
}
if (!result_complete_sort_cases_sector) {
	var result_complete_sort_cases_sector=0;
}

function sort_cases(the_id){

    if (result_complete_sort_cases==2 || result_complete_sort_cases==0) {
        result_complete_sort_cases=1;

	// Initialize variables early so we can use them from the start of the program
	var deptName = "";
	var dataArray;
	var count = 0;
	var money = "";

	$.ajax({
			url: '/admin/wallboard/apitest/'+the_id, // point to server-side PHP script
			dataType: 'json',  // what to expect back from the PHP script, if anything
			cache: true,
			contentType: false,
			processData: false,
		}).done(function(res){



			if (the_id=="cases_report_day"){

				$(".casesToday").html("");
				$(".casesToday").append('<tr style="background-color:rgba(255,255,255,0.1); color:#fff;"><th>Client</th><th>Number of Cases</th><th>Total Value of Cases</th></tr>');

				// Run through all of the departments that we've been given
				for (department in res.data){

					// Push the arrays held in the current department into a new array so that it's easier to process
					dataArray = res.data[department];

					// Make a header for the current department, then deposit a row of data for each entry into the department.
					$(".casesToday").append('<tr style="background-color:rgba(255,255,255,0.1); color:#fff;"><th>'+department+'</th><th></th><th></th></tr>');

					for (count = 0; count < dataArray.length; count++) {


							money = "£"+numberWithThous(dataArray[count][3]);


						$(".casesToday").append('<tr>'+
															'<td>'+dataArray[count][1]+'</td>'+
															'<td>'+dataArray[count][2]+'</td>'+
															'<td>'+money+'</td>'+
															'</tr>');

					}
				}
			}

            result_complete_sort_cases=2;
		}).fail(function(e){
			console.log(e);
		});

    }

}
function sort_cases_sector(the_id){

    if (result_complete_sort_cases_sector==2 || result_complete_sort_cases_sector==0) {
        result_complete_sort_cases_sector=1;

	// Initialize variables early so we can use them from the start of the program
	var deptName = "";
	var dataArray;
	var count = 0;
	var money = "";

	$.ajax({
			url: '/admin/wallboard/apitest/'+the_id, // point to server-side PHP script
			dataType: 'json',  // what to expect back from the PHP script, if anything
			cache: true,
			contentType: false,
			processData: false,
		}).done(function(res){



			if (the_id=="cases_report_day_sector"){

				$(".sectorcasesToday").html("");
				$(".sectorcasesToday").append('<tr style="background-color:rgba(255,255,255,0.1); color:#fff;"><th>Sector</th><th>Number of Cases</th><th>Total Value of Cases</th></tr>');

				// Run through all of the departments that we've been given
				for (department in res.data){
                    $(".sectorcasesToday").append(
                        "<tr>"+
                        "<td>"+department+"</td>"+
                        "<td>"+res.data[department][0][1]+"</td>"+
                        "<td>£"+res.data[department][0][2]+"</td>"+
                        "</tr>"
                    )
				}
			}

            result_complete_sort_cases_sector=2;
		}).fail(function(e){
			console.log(e);
		});

    }
}
</script>
