<style>


.mod-paddingleftbw3 {
    padding-left: 238px !important;
}
.mod-poundsign{
	position: absolute!important;
    top: 14px !important;
    left: 165px !important;
}
.mod-flip-clock-wrapper ul {
    width: 78px !important;
    height: 134px !important;
}

.mod-flip-clock-wrapper ul li a div div .mod-inn{
    padding-top: 23px !important;
    font-size: 109px !important;
}
.mod-inn{
	padding-top: 23px !important;
	font-size: 109px !important;
}
.mod-flip-clock-wrapper ul li a div div{
	padding-top: 23px !important;
	font-size: 109px !important;
}
.mod-clock, .mod-clock2, .mod-clock3, .mod-clock4 {
	padding-top: 25px !important;
}
.mod-header-bar-col-6 .mod-title {
	right: -331px !important;
}
.sectorbuisness td{
	padding-right: 10px;
	padding-top: 10px;
	padding-bottom: 10px;
	font-size: 30px;
}
.sectorbuisnessheaders th{
	padding: 10px !important;
}

</style>
<div class="container-fluid">
	<div class="row">
		<div class="col-6">
			<div class="container-fluid">
				<div class="row">
					<div class="col-md-4 mt-3">
						<div class="col-md-12">
							<h2 class="header-bar-col-6 mod-header-bar-col-6"><span class="symbol"><i class="fas fa-pound-sign"></i></span> <span class="title mod-title">Cash Collected Today</span></h2>
						</div>
			        </div>
				</div>
			</div>


			<div class="container-fluid">
				<div class="bw_mt-4 row">
					<div class="col-md-12 offset-md-0">
						<div class="col-md-12">
							<div class="flip-clock-wrapper mod-flip-clock-wrapper poundsign mod-poundsign">
								<ul class="flip "><li class="flip-clock-before"><a href="#"><div class="up"><div class="shadow"></div><div class="inn mod-inn">0</div></div><div class="down"><div class="shadow"></div><div class="inn mod-inn">0</div></div></a></li><li class="flip-clock-active"><a href="#"><div class="up"><div class="inn mod-inn">£</div></div><div class="down"><div class="inn mod-inn">£</div></div></a></li></ul>
							</div>
							<div class="clock mod-clock paddingleftbw3 mod-paddingleftbw3 mod-flip-clock-wrapper"></div>
						</div>
			        </div>
				</div>
			</div>

			<div class="container-fluid">
				<div class="row pt-3">
					<div class="col-md-4 mt-3">
						<div class="col-md-12">
							<h2 class="header-bar-col-6 mod-header-bar-col-6"><span class="symbol"><i class="fas fa-pound-sign"></i></span> <span class="title mod-title">Cash Collected Month</span></h2>
						</div>
			        </div>
				</div>
			</div>


			<div class="container-fluid">
				<div class="bw_mt-4 row">
					<div class="col-md-12 offset-md-0">
						<div class="col-md-12">
							<div class="flip-clock-wrapper mod-flip-clock-wrapper poundsign mod-poundsign">
								<ul class="flip "><li class="flip-clock-before"><a href="#"><div class="up"><div class="shadow"></div><div class="inn mod-inn">0</div></div><div class="down"><div class="shadow"></div><div class="inn mod-inn">0</div></div></a></li><li class="flip-clock-active"><a href="#"><div class="up"><div class="inn mod-inn">£</div></div><div class="down"><div class="inn mod-inn">£</div></div></a></li></ul>
							</div>
							<div class="clock2 mod-clock2 paddingleftbw3 mod-paddingleftbw3 mod-flip-clock-wrapper">
							</div>
						</div>
			        </div>
				</div>
			</div>



			<div class="container-fluid">
				<div class="row">
					<div class="col-md-4 mt-3">
						<div class="col-md-12">
							<h2 class="header-bar-col-6 mod-header-bar-col-6"><span class="symbol"><i class="fas fa-pound-sign"></i></span> <span class="title mod-title">Revenue Collected Today</span></h2>
						</div>
			        </div>
				</div>
			</div>


			<div class="container-fluid">
				<div class="bw_mt-4 row">
					<div class="col-md-12 offset-md-0">
						<div class="col-md-12">
							<div class="flip-clock-wrapper mod-flip-clock-wrapper poundsign mod-poundsign">
								<ul class="flip "><li class="flip-clock-before"><a href="#"><div class="up"><div class="shadow"></div><div class="inn mod-inn">0</div></div><div class="down"><div class="shadow"></div><div class="inn mod-inn">0</div></div></a></li><li class="flip-clock-active"><a href="#"><div class="up"><div class="inn mod-inn">£</div></div><div class="down"><div class="inn mod-inn">£</div></div></a></li></ul>
							</div>
							<div class="clock3 mod-clock3 paddingleftbw3 mod-paddingleftbw3 mod-flip-clock-wrapper"></div>
						</div>
			        </div>
				</div>
			</div>

			<div class="container-fluid">
				<div class="row pt-3">
					<div class="col-md-4 mt-3">
						<div class="col-md-12">
							<h2 class="header-bar-col-6 mod-header-bar-col-6"><span class="symbol"><i class="fas fa-pound-sign"></i></span> <span class="title mod-title">Revenue Collected Month</span></h2>
						</div>
			        </div>
				</div>
			</div>


			<div class="container-fluid">
				<div class="bw_mt-4 row">
					<div class="col-md-12 offset-md-0">
						<div class="col-md-12">
							<div class="flip-clock-wrapper mod-flip-clock-wrapper poundsign mod-poundsign">
								<ul class="flip "><li class="flip-clock-before"><a href="#"><div class="up"><div class="shadow"></div><div class="inn mod-inn">0</div></div><div class="down"><div class="shadow"></div><div class="inn mod-inn">0</div></div></a></li><li class="flip-clock-active"><a href="#"><div class="up"><div class="inn mod-inn">£</div></div><div class="down"><div class="inn mod-inn">£</div></div></a></li></ul>
							</div>
							<div class="clock4 mod-clock4 paddingleftbw3 mod-paddingleftbw3 mod-flip-clock-wrapper">
							</div>
						</div>
			        </div>
				</div>
			</div>
		</div>



		<div class="col-6">
			<div class="container-fluid">
				<div class="row">
					<div class="col-md-12">
						<h2 class="header-bar-col-6 mod-header-bar-col-6"><span class="symbol"><i class="fas fa-pound-sign"></i></span></h2>
						<div class="row row_data" style="height:500px; padding-right:50px;">
							<div class="col-md-12">
												<div class="card card-blue-white mt-0">
												<h5 class="card-header">Business By Sector MTD</h5><div class="card-body p-0">
												<div>
													<table style="width:100%;" class="revToday BS">
													<tr class="sectorbuisnessheaders" style="background-color:#002649; color:#fff; font-size: 25px;"><th>Sector</th><th>Total Cash <br> Collected</th><th>Total Revenue</th></tr>
													<tbody class="sectorbuisness">

													</tbody>
													</table>
												</div>
											</div>
										</div>
							</div>
						</div>
					</div>
				</div>
			</div>


		</div>
	</div>
</div>
