<style>

.clock{
	padding-top:250px;
}

</style>

					

					
					
					
<div class="container-fluid">
	<div class="bw_mt-4 row">
		<div class="col-md-12 offset-md-0">
			<div class="col-md-12">
										
				<h2 class="header-bar-col-6"><span class="symbol"><i class="fas fa-briefcase"></i></span> <span class="title">New Cases This Month</span></h2>
										
			</div>				
			<div class="clock" style="margin:2em;"></div>
				
		</div>
	</div>
</div>

