<style>

.BS th, .BS td {
	width:33%;
}

div.quartCard {
	padding-left: 6px;
	padding-right: 6px;
}

</style>

<div class="container-fluid">
	<h2 class=""><span>White Label Email Boards</span></h2>
	<div class="row">
		<div class="col-md-7 mt-3">
			<div class="col-md-12">
				<h2 class="ticket-title bounding-screen2"><span>White Label Zendesk Ticket Views</span></h2>

				<div class="row row_datascreen12" style="height:390px">


				</div>

			</div>


		</div>
	</div>
</div>

<script>

function group_update_tickets_BZ(the_id) {
	var textcolor = '';
	$.ajax({
			url: '/admin/wallboard/apitest/'+the_id, // point to server-side PHP script
			dataType: 'json',  // what to expect back from the PHP script, if anything
			cache: true,
			contentType: true,
			processData: false,
			success: function(res){
				$('.row_datascreen12').empty()
				Object.keys(res).forEach(function(mailbox,value){
					if (res[mailbox]['total'] > 50) {
						textcolor = 'text-warning';
					}
					if (res[mailbox]['total'] > 100) {
						textcolor = 'text-danger';
					}
					$('.row_datascreen12').append('<div class="col-md-4"><div class="card-background-crs mt-0 m-1"><h5 class="card-header mt-0" style="font-size:16px; ">'+mailbox+'</h5><div class="card-body p-0"><div style="line-height:25px; padding-top:20px; padding-bottom:20px; text-align:center;"><span class="zen_text">'+res[mailbox]['total']+'</span><div style="font-size:25px"><b>open</b></div></div></div><div class="card-footer date_text">Oldest Email<br><span class="ticket">'+res[mailbox]['old']+'</span></div></div></div>')
					textcolor = '';
				})
			}
		});

}


</script>
