<style>

.mod-flip-clock-wrapper ul {
    width: 78px !important;
    height: 134px !important;
}

.mod-flip-clock-wrapper ul li a div div .mod-inn{
    padding-top: 23px !important;
    font-size: 109px !important;
}
.mod-inn{
	padding-top: 23px !important;
	font-size: 109px !important;
}
.mod-flip-clock-wrapper ul li a div div{
	padding-top: 23px !important;
	font-size: 109px !important;
}
.mod-clock, .mod-clock2, .mod-clock3, .mod-clock4 {
	padding-top: 25px !important;
}
.mod-header-bar-col-6 .mod-title {
	right: -65px !important;
}

.mod-right{
  right: -100px;
}

.sectorbuisness td{
	padding-right: 10px;
	padding-top: 10px;
	padding-bottom: 10px;
	font-size: 20px;
}
.sectorbuisnessheaders th{
	padding: 10px !important;
}

</style>
<div class="container-fluid">
  <div class="row">
      <div class="col-md-12 title" style="margin-bottom: 20px">Cash and Revenue Board</div>
      <div class="col-6">
        <div class="col-md-12">

          <h2 class="mod-header-bar-col-6-jg bounding-screen2"><span class="subtitle mod-title">Cash Collected Today</span></h2>

          <div class="bw_mt-4 row">
            <div class="col-md-12">
              <div class="flip-clock-wrapper mod-flip-clock-wrapper poundsign mod-poundsignjg">
              <ul class="flip "><li class="flip-clock-before"><a href="#"><div class="up"><div class="shadow"></div><div class="inn mod-inn">0</div></div><div class="down"><div class="shadow"></div><div class="inn mod-inn">0</div></div></a></li><li class="flip-clock-active"><a href="#"><div class="up"><div class="inn mod-inn">£</div></div><div class="down"><div class="inn mod-inn">£</div></div></a></li></ul>
              </div>
              <div class="clock mod-clock mod-paddingleftjg mod-flip-clock-wrapper"></div>
            </div>
          </div>

          <h2 class="mod-header-bar-col-6-jg bounding-screen2"><span class="subtitle mod-title">Cash Collected Month</span></h2>

          <div class="bw_mt-4 row">
              <div class="col-md-12">
                <div class="flip-clock-wrapper mod-flip-clock-wrapper poundsign mod-poundsignjg">
                  <ul class="flip "><li class="flip-clock-before"><a href="#"><div class="up"><div class="shadow"></div><div class="inn mod-inn">0</div></div><div class="down"><div class="shadow"></div><div class="inn mod-inn">0</div></div></a></li><li class="flip-clock-active"><a href="#"><div class="up"><div class="inn mod-inn">£</div></div><div class="down"><div class="inn mod-inn">£</div></div></a></li></ul>
                </div>
                <div class="clock2 mod-clock2 mod-paddingleftjg mod-flip-clock-wrapper"></div>
              </div>
          </div>


          <h2 class="mod-header-bar-col-6-jg bounding-screen2"><span class="subtitle mod-title">Revenue Collected Today</span></h2>

          <div class="bw_mt-4 row">
              <div class="col-md-12">
                <div class="flip-clock-wrapper mod-flip-clock-wrapper poundsign mod-poundsignjg">
                  <ul class="flip "><li class="flip-clock-before"><a href="#"><div class="up"><div class="shadow"></div><div class="inn mod-inn">0</div></div><div class="down"><div class="shadow"></div><div class="inn mod-inn">0</div></div></a></li><li class="flip-clock-active"><a href="#"><div class="up"><div class="inn mod-inn">£</div></div><div class="down"><div class="inn mod-inn">£</div></div></a></li></ul>
                </div>
                <div class="clock3 mod-clock3 mod-paddingleftjg mod-flip-clock-wrapper"></div>
              </div>
          </div>


          <h2 class="mod-header-bar-col-6-jg bounding-screen2"><span class="subtitle mod-title">Revenue Collected Month</span></h2>

          <div class="bw_mt-4 row">
              <div class="col-md-12">
                <div class="flip-clock-wrapper mod-flip-clock-wrapper poundsign mod-poundsignjg">
                  <ul class="flip "><li class="flip-clock-before"><a href="#"><div class="up"><div class="shadow"></div><div class="inn mod-inn">0</div></div><div class="down"><div class="shadow"></div><div class="inn mod-inn">0</div></div></a></li><li class="flip-clock-active"><a href="#"><div class="up"><div class="inn mod-inn">£</div></div><div class="down"><div class="inn mod-inn">£</div></div></a></li></ul>
                </div>
                <div class="clock4 mod-clock4 mod-paddingleftjg mod-flip-clock-wrapper"></div>
              </div>
          </div>
          


        </div>
      </div>
      <div class="col-6">
        <div class="col-md-12">

          <div class="card transparent">
            <h2 class="card-header borderbottom mt-0" class="subtitle">Business By Sector MTD</h2>
            <table style="width:100%;" class="revToday BS">
            <tr class="sectorbuisnessheaders"><th>Sector</th><th>Total Cash<br>Collected</th><th>Total Revenue</th></tr>
            <tbody class="sectorbuisness">

            </tbody>
            </table>
          </div>

        </div>
      </div>
  </div>
</div>
