<style>

.clock2{
	padding-top:50px;
}

.clock3{
	padding-top:50px;
}

.paddingleftbw3{
	padding-left:95px;
}
.poundsign{
	position: absolute!important;
    top: 39px;
    left: 20px;
}
</style>


<div class="container-fluid">
	<div class="row">
		<div class="col-md-4 mt-3">
			<div class="col-md-12">
				<h2 class="header-bar-col-6"><span class="symbol"><i class="fas fa-pound-sign"></i></span> <span class="title">Cash Collected Today</span></h2>
			</div>
        </div>
	</div>
</div>


<div class="container-fluid">
	<div class="bw_mt-4 row">
		<div class="col-md-12 offset-md-0">
			<div class="col-md-12">
				<div class="flip-clock-wrapper poundsign">
					<ul class="flip "><li class="flip-clock-before"><a href="#"><div class="up"><div class="shadow"></div><div class="inn">0</div></div><div class="down"><div class="shadow"></div><div class="inn">0</div></div></a></li><li class="flip-clock-active"><a href="#"><div class="up"><div class="inn">£</div></div><div class="down"><div class="inn">£</div></div></a></li></ul>
				</div>
				<div class="clock2 paddingleftbw3"></div>
			</div>
        </div>
	</div>
</div>

<div class="container-fluid">
	<div class="row pt-3">
		<div class="col-md-4 mt-3">
			<div class="col-md-12">
				<h2 class="header-bar-col-6"><span class="symbol"><i class="fas fa-pound-sign"></i></span> <span class="title">Cash Collected Month</span></h2>
			</div>
        </div>
	</div>
</div>


<div class="container-fluid">
	<div class="bw_mt-4 row">
		<div class="col-md-12 offset-md-0">
			<div class="col-md-12">
				<div class="flip-clock-wrapper poundsign">
					<ul class="flip "><li class="flip-clock-before"><a href="#"><div class="up"><div class="shadow"></div><div class="inn">0</div></div><div class="down"><div class="shadow"></div><div class="inn">0</div></div></a></li><li class="flip-clock-active"><a href="#"><div class="up"><div class="inn">£</div></div><div class="down"><div class="inn">£</div></div></a></li></ul>
				</div>
				<div class="clock3 paddingleftbw3">
				</div>
			</div>
        </div>
	</div>
</div>
