<style media="screen">
	.sage{
		font-size: 30px !important;
		line-height: 10px !important;
		height: 40px !important;
	}
</style>

<?php

//var_dump($this->googlestat);

// <?php $rowt=0; $rowt=(($row->users-$row->login)/$row->users)*100; echo number_format($rowt,2); $rowtt=$rowtt+$rowt;  ?>%

<?php
$payment_success = $this->googlestat[0]->payments;

$users = $this->googlestat[0]->users;
$login = $this->googlestat[0]->login;
$dropoff=(($users-$login)/$users)*100;

$success=($payment_success/$login)*100;

// echo 'dropoff is: '.ceil($dropoff).' and payment success is: '.$success;
//
// echo '<pre style="color:white;">';
// echo print_r($this->googlestat);
// echo '</pre>';
 ?>

<div class="container-fluid">
	<h2 class=""><span>MyCRS Board</span></h2>
	<div class="row">
		<div class="col-md-6">
			<div class="col-md-12 mt-0">
				<h2 class="ticket-title bounding-screen2">Active Users on myCRS</span></h2>
				<div class="row_data">
					<ul class="people_online">
					<li><i class="fas fa-male"></i></li>
					</ul>
					<div class="online_usersa update_fields update_glive" id="update_glive">
						Updating
					</div>
				</div>

			</div>
			<div class="col-md-12">

        <h2 class="ticket-title bounding-screen2">LiveChat</span></h2>

				<div class="row row_data cash_crs">

					<div class="col-md-4 chats_today2">
						<div class="card-background-crs box">
						<h3>Chats Today</h3>
						<div class="circle_outline_zen circle_outline_chats span"><span class="chats_today" >0</span></div>
					</div>
					</div>

					<div class="col-md-4 chats_thisweek2">
						<div class="card-background-crs box">
						<h3>Chats This Week</h3>
						<div class="circle_outline_zen circle_outline_chats span"><span class="chats_week" >0</span></div>
					</div>
					</div>

					<div class="col-md-4 chats_thismonth2">
						<div class="card-background-crs box">
						<h3>Chats This Month</h3>
						<div class="circle_outline_zen circle_outline_chats span"><span class="chats_month">0</span></div>
					</div>
					</div>
				</div>
			</div>
			<br>

			<div class="col-md-12">
				<h2 class="ticket-title bounding-screen2">Active Users on LiveChat</span></h2>
				<div class="row_data">
					<ul class="users_online">
					<li><i class="fas fa-male"></i></li>
					</ul>
					<div class="online_usersa user_no" id="test_test">
						Updating
					</div>
				</div>

			</div>

		</div>
		<div class="col-md-6">

			<div class="col-md-12" style="margin-bottom: 60px !important;">
				<h2 class="ticket-title bounding-screen2">Arrangements Online TEST</span></h2>

				<div class="row row_data cash_crs">

					<div class="col-md-4">
						<div class="card-background-crs box">
						<h3>Today</h3>
						<div class="circle_outline_zen span"><span class="tt_arrangements">0</span></div>
					</div>
					</div>
					<div class="col-md-4">
						<div class="card-background-crs box">
						<h3>This Week</h3>
						<div class="circle_outline_zen span"><span class="tw_arrangements">0</span></div>
					</div>
					</div>
					<div class="col-md-4">
						<div class="card-background-crs box">
						<h3>This Month</h3>
						<div class="circle_outline_zen span"><span class="tm_arrangements">0</span></div>
					</div>
					</div>
				</div>
			</div>


			<div class="col-md-12">
				<h2 class="ticket-title bounding-screen2">Website Visits</span></h2>

				<div class="row row_data cash_crs">

					<div class="col-md-4">
						<h3>Today</h3>
						<canvas height="250" width="700" id="canvas_c"></canvas>
					</div>
					<div class="col-md-4">
						<h3>This Week</h3>
						<canvas height="250" width="700" id="canvas_d"></canvas>
					</div>
					<div class="col-md-4">
						<h3>This Month</h3>
						<canvas height="250" width="700" id="canvas_e"></canvas>
					</div>
				</div>
			</div>

			<div class="col-md-12">
				<h2 class="ticket-title bounding-screen2">Drop off and payment success</span></h2>

				<div class="row cash_crs">

					<div class="col-md-6 text-center">
						<h1 style="color:white;">Dropoff</h1>
						<h2 class="dollar" style="color:white;"><?php echo ceil($dropoff); ?>%</h2>
					</div>

					<div class="col-md-6 text-center">
						<h1 style="color:white;">Payment success</h1>
						<h2 class="dollar" style="color:white;"><?php echo $payment_success; ?>%</h2>
					</div>

				</div>



			</div>

			<script>
			$(".dollar").effect("bounce", { times:10 }, 5000);
			</script>


			<div class="col-md-12">
				<h2 class="ticket-title bounding-screen2">Cash Collected on myCRS</span></h2>

				<div class="row row_data cash_crs">

					<div class="col-md-4">
						<div class="card-background-crs box">
						<h3>Today</h3>
						<div class="circle_outline_zen span money"><span class="tt_cashcollected">0</span></div>
					</div>
					</div>
					<div class="col-md-4">
						<div class="card-background-crs box">
						<h3>This Week</h3>
						<div class="circle_outline_zen span money"><span class="tw_cashcollected">0</span></div>
					</div>
					</div>
					<div class="col-md-4">
						<div class="card-background-crs box">
						<h3>This Month</h3>
						<div class="circle_outline_zen span money"><span class="tm_cashcollected">0</span></div>
					</div>
					</div>
				</div>
			</div>

			<div class="col-md-12">
				<h2 class="ticket-title bounding-screen2">Number of Payments on myCRS</span></h2>

				<div class="row row_data cash_crs">

					<div class="col-md-4">
						<div class="card-background-crs box">
						<h3>Today</h3>
						<div class="circle_outline_zen span money"><span class="sage tt_payments">0</span><span class="sage tt_failure_payments">0</span></div>
					</div>
					</div>
					<div class="col-md-4">
						<div class="card-background-crs box">
						<h3>This Week</h3>
						<div class="circle_outline_zen span money"><span class="sage tw_payments">0</span><span class="sage tw_failure_payments">0</span></div>
					</div>
					</div>
					<div class="col-md-4">
						<div class="card-background-crs box">
						<h3>This Month</h3>
						<div class="circle_outline_zen span money"><span class="sage tm_payments">0</span><span class="sage tm_failure_payments">0</span></div>
					</div>
					</div>
				</div>
			</div>


		</div>
	</div>
</div>

<?php if (date('Y-m-d')==date('Y-10-31')) {
$colora="#000000";
$colorb="#000000";
$colorc="#000000";
} else {
$colora="#00b7c6";
$colorb="#7A7A7A";
$colorc="#dadf00";
} ?>

<script>
function group_update_onsite(the_id) {
	$.ajax({
			url: '/admin/wallboard/api/'+the_id, // point to server-side PHP script
			dataType: 'text',  // what to expect back from the PHP script, if anything
			cache: true,
			contentType: true,
			processData: true,
		}).done(function(res){ //

			if (res>25) {
				$('.people_online').css("font-size", "50px");
			} else {
				$('.people_online').css("font-size", "75px");
			}

			var cookiecount = getCookie('active_users');

			var check = getCookie('swalfire');

			if (res>50 && check === null) {

				setCookie('swalfire','1','1');

							var current_value = parseInt(getCookie('active_users'))+parseInt("1");
							let timerInterval
							Swal.fire({
								title: 'Active Users on myCRS',
								html: '<span class="cashcollected">'+numberWithThous(res)+' Users online. </span><br><img src="https://media2.giphy.com/media/yPhqlJccIOaru/giphy.gif?cid=ecf05e4762kjjfq22wu1ebcx4wbw7laygp3uiahrrm3as4j1&rid=giphy.gif" class="img-fluid"> <br>I will close in <b></b> milliseconds.',
								timer: 30500,
								backdrop: true,
								padding: '100px',
								heightAuto: true,
								timerProgressBar: true,
								onBeforeOpen: () => {
									Swal.showLoading()

									create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000));
									create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000));
									create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000));
									create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000));
									create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000));
									create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000));
									create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000));
									create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000));
									create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000));
									create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000));
									create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000));
									create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000));
									create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000)); create(Math.ceil(Math.random() * 10000));

									timerInterval = setInterval(() => {
										Swal.getContent().querySelector('b')
											.textContent = Swal.getTimerLeft()
									}, 100)
								},
								onClose: () => {
									clearInterval(timerInterval)
								}
							}).then((result) => {
								if (
									/* Read more about handling dismissals below */
									result.dismiss === Swal.DismissReason.timer
								) {
									console.log('I was closed by the timer') // eslint-disable-line
								}
							})
			}

			var i;
			$('.people_online').empty();

			for (i = 0; i < res; i++) {

				if(res < 10){
					$('.people_online').append('<li><i style="color:#FFFFFF;" class="fas fa-male"></i></li>');
				}
				if(res > 10 && res < 20){
					$('.people_online').append('<li><i style="color:#EBFE03;" class="fas fa-male"></i></li>');
				}
				if(res > 20){
					$('.people_online').append('<li><i style="color:#74FE01;" class="fas fa-male"></i></li>');
				}
				// $(".people_online").effect("bounce", { times:3 }, 3000);

				// $('.people_online').append('<li><i style="color:#7DFD05;" class="fas fa-male"></i></li>');
			}

			if(res < 10){
				$( ".people_online" ).effect( "shake", {times:6}, 5000 );
			}
			if(res > 10 && res < 20){
				$(".people_online").effect("bounce", { times:4 }, 15000)
			}
			if(res > 20){
				$(".people_online").effect("bounce", { times:2 }, 10000)
			}

			//$( ".people_online" ).toggle( "bounce", { mode:show, times: 0 }, "slow" );

				$("."+the_id).html(res);

				//setTimeout(worker, 5000);
		});
}

function group_update_livechat(the_id) {
	$.ajax({
			url: '/admin/wallboard/api/'+the_id, // point to server-side PHP script
			dataType: 'json',  // what to expect back from the PHP script, if anything
			cache: true,
			contentType: true,
			processData: true,
		}).done(function(res){

			// construct each class as html input, containing the total number of chats and the average response time
			// the main goal of the tc_text and rc_text classes is to regulate spacing between the data in the circles
			if(res.chats_today > 100 ){

// $('.chats_today2').addClass('col-md-12').removeClass('col-md-4',10000,function(){
//
// 	$('.chats_thisweek2').hide();
// 	$('.chats_thismonth2').hide();
//
//
// });

// $('.chats_today2').html('Reached over 100 chats today!');

// $('.chats_today2').fadeOut(200).fadeIn(200,function(){
//
// 	setTimeout(function() {
// 		$('.chats_today2').addClass('col-md-4').removeClass('col-md-12');
//
// 		$('.chats_today2').hide();
//
// 		$('.chats_thisweek2').addClass('col-md-12').removeClass('col-md-4',10000,function(){
//
// 			$('.chats_thisweek2').css( "color", "black");
//
// 		});
//
// 		// $('.chats_today2').html('Reached over 100 chats today!');
//
// 		$('.chats_thisweek2').fadeOut(200).fadeIn(200,function(){
//
// 			setTimeout(function() {
// 				$('.chats_thisweek2').addClass('col-md-4').removeClass('col-md-12');
//
// 				$('.chats_thisweek2').show();
// 				$('.chats_today2').show();
// 				$('.chats_thismonth2').show();
// 			},10000);
// 		});
//
// 	},10000);
// });

			}

			$('.chats_today').html("<div class='tc_text'>" + res.chats_today+
											  "<div class='rt_text'><h6>Average Response Time:</h6>"
											  + res.avrg_RT_day + "</div></div>");

			$('.chats_week').html("<div class='tc_text'>" + res.chats_week +
											  "<div class='rt_text'><h6>Average Response Time:</h6>"
											  + res.avrg_RT_week + "</div></div>");

			$('.chats_month').html("<div class='tc_text'>" + res.chats_month +
											  "<div class='rt_text'><h6>Average Response Time:</h6>"
											  + res.avrg_RT_month + "</div></div>");


			if (res.live_users>25) {
				$('.users_online').css("font-size", "50px");
			} else {
				$('.users_online').css("font-size", "75px");
			}

			var i;
			$('.users_online').empty();
			for (i = 0; i < res.live_users; i++) {

				if(res.live_users < 10){
					$('.users_online').append('<li><i style="color:#FFFFFF;" class="fas fa-male"></i></li>');
				}
				if(res.live_users > 10 && res < 20){
					$('.users_online').append('<li><i style="color:#EBFE03;" class="fas fa-male"></i></li>');
				}
				if(res.live_users > 20){
					$('.users_online').append('<li><i style="color:#74FE01;" class="fas fa-male"></i></li>');
				}

				//$('.users_online').append('<li><i class="fas fa-male"></i></li>');
			}

			if(res.live_users < 10){
				$( ".users_online" ).effect( "shake", {times:10}, 3000 );
			}
			if(res.live_users > 10 && res.live_users < 20){
				$(".users_online").effect("bounce", { times:7 }, 3000)
			}
			if(res.live_users > 20){
				$(".users_online").effect("bounce", { times:15 }, 3000)
			}

			$(".user_no").html(res.live_users);
		});


}

function group_update(the_id) {
	$.ajax({
			url: '/admin/wallboard/api/'+the_id, // point to server-side PHP script
			dataType: 'json',  // what to expect back from the PHP script, if anything
			cache: true,
			contentType: true,
			processData: true,
		}).done(function(res){ //

			//alert(res);

			//console.log(res);

			$('.tt_arrangements').html(res.arrangement.today);

			// if(res.arrangement.today > 100){
			//
			// 	$('.arrangements_today').addClass('col-md-12 bannercard').removeClass('col-md-4',10000,function(){
			//
			// 		$('.arrangements_today').css( "color", "black");
			//
			// 	});
			//
			// 	// $('.chats_today2').html('Reached over 100 chats today!');
			//
			// 	$('.arrangements_today').fadeOut(200).fadeIn(200,function(){
			//
			// 		setTimeout(function() {
			// 			$('.arrangements_today').addClass('col-md-4').removeClass('col-md-12 bannercard');
			// 		},20000);
			// 	});
			//
			// }

			$('.tw_arrangements').html(res.arrangement.week);
			$('.tm_arrangements').html(res.arrangement.month);

			//console.log(res.cashcollected.today);

			$('.tt_cashcollected').html(res.cashcollected.today);
			$('.tw_cashcollected').html(res.cashcollected.week);
			$('.tm_cashcollected').html(res.cashcollected.month);

			number = 0;

			$('.tt_payments').html('Successful: '+res.sagepay.today.SUCCESS);
			$('.tw_payments').html('Successful: '+res.sagepay.week.SUCCESS);
			$('.tm_payments').html('Successful: '+res.sagepay.month.SUCCESS);

			$('.tt_failure_payments').html('Failed: '+res.sagepay.today.FAILURE);
			$('.tw_failure_payments').html('Failed: '+res.sagepay.week.FAILURE);
			$('.tm_failure_payments').html('Failed: '+res.sagepay.month.FAILURE);

			$('.today_visits').html(res.today.users);
			//alert(res.today.users);
			today_donut.data.datasets[0].data = res.today_data;
			today_donut.options.scales.yAxes[0].ticks.max = parseInt(res.today_data[0])+parseInt(100);
			today_donut.update();

			week_donut.data.datasets[0].data = res.week_data;
			week_donut.options.scales.yAxes[0].ticks.max = parseInt(res.week_data[0])+parseInt(1000);
			week_donut.update();

			month_donut.data.datasets[0].data = res.month_data;
			month_donut.options.scales.yAxes[0].ticks.max = parseInt(res.month_data[0])+parseInt(4000);
			month_donut.update();

			//console.log(res.today_data);
			//console.log(res.week_data);
			//console.log(res.month_data);
			//console.log(res.arrangement);
			//console.log(res.cashcollected);
			//console.log(res.today);
		});
}


var today_donut_data = {
		labels: ["Users","New Users"],
		datasets: [{
			borderWidth: 1,
			backgroundColor: ['<?php echo $colora; ?>','<?php echo $colorb; ?>','<?php echo $colorc; ?>'],
			borderColor: ['<?php echo $colora; ?>','<?php echo $colorb; ?>','<?php echo $colorc; ?>'],
			data:[100,80,20]
		}]

	};
var today_donut_opt = {
		type: 'bar',
		data: today_donut_data,
		options: {
			plugin_attribute:2,
			responsive: true,
			legend: {
				display: false
			},
			title: {
				display: false
			},
			scales: {
			   xAxes: [{
					ticks: {
						fontSize: 14,
						fontStyle:'bold',
						fontColor:'#fff'
					}
			  }],
			  yAxes: [{
					display: false,
					ticks: {
						max:2000,
						fontSize: 10,
						fontStyle:'bold',
						fontColor:'#fff'
					}
			  }]
			}
		}
	};
var week_donut_data = {
		labels: ["Users","New Users"],
		datasets: [{
			borderWidth: 1,
			backgroundColor: ['<?php echo $colora; ?>','<?php echo $colorb; ?>','<?php echo $colorc; ?>'],
			borderColor: ['<?php echo $colora; ?>','<?php echo $colorb; ?>','<?php echo $colorc; ?>'],
			data:[100,80,20]
		}]

	};
var week_donut_opt = {
		type: 'bar',
		data: week_donut_data,
		options: {
			plugin_attribute:2,
			responsive: true,
			legend: {
				display: false
			},
			title: {
				display: false
			},
			scales: {
			   xAxes: [{
					ticks: {
						fontSize: 11,
						fontStyle:'bold',
						fontColor:'#fff'
					}
			  }],
			  yAxes: [{
					display: false,
					ticks: {
						fontSize: 10,
						fontStyle:'bold',
						fontColor:'#fff'
					}
			  }]
			}
		}
	};
var month_donut_data = {
		labels: ["Users","New Users"],
		datasets: [{
			borderWidth: 1,
			backgroundColor: ['<?php echo $colora; ?>','<?php echo $colorb; ?>','<?php echo $colorc; ?>'],
			borderColor: ['<?php echo $colora; ?>','<?php echo $colorb; ?>','<?php echo $colorc; ?>'],
			data:[1001,80,20]
		}]

	};
var month_donut_opt = {
		type: 'bar',
		data: month_donut_data,
		options: {
			plugin_attribute:2,
			responsive: true,
			legend: {
				display: false
			},
			title: {
				display: false
			},
			scales: {
			   xAxes: [{
					ticks: {
						fontSize: 10,
						fontStyle:'bold',
						fontColor:'#fff'
					}
			  }],
			  yAxes: [{
					display: false,
					ticks: {
						fontSize: 10,
						fontStyle:'bold',
						fontColor:'#fff'
					}
			  }]
			}
		}
	};
</script>
