<?php

if (date('Y-m-d')==date('Y-10-31')) { $color="#000000"; } else { $color="#002649"; }

$month_tcolor = "#ffe900";
$percent_color = "#00b7c6";

?>
<script>

// When you're arranging a dataset for a line + bar chart put the data set for the line first, otherwise the line will be drawn behind the bars
var barChartData_f = {
	labels: [],
	datasets: [{
		label: 'Monthly Target',
		type:"line",
		stack: "2",
		borderWidth: 2,
		backgroundColor: 'rgba(255, 218, 35, 0)', // set the background color to invisible on all lines
		borderColor: '<?php echo $percent_color; ?>',
		data:[]
	},
	{
		label: 'Revenue Collected this Month',
		stack: "1",
		borderWidth: 1,
		backgroundColor: '<?php echo $color; ?>',
		borderColor: '<?php echo $color; ?>',
		data:[]
	},
	{
		label: 'Forecast Revenue this Month',
		stack: "1",
		borderWidth: 1,
        backgroundColor: '#7a7a7a',
		borderColor: '<?php echo $color; ?>',
		data:[]
	}
]

};

var barChartData_g = {
	labels: [],
	datasets: [{
		label: 'Revenue Phasing %',
		type: 'line',
		stack: "0",
		borderWidth: 2,
		backgroundColor: 'rgba(255, 218, 35, 0)',
		borderColor: '<?php echo $color; ?>',
		data:[]
	},
    {
        label: 'Revenue + Forecasted Phasing %',
        type: 'line',
        stack: "0",
        borderWidth: 2,
        backgroundColor: 'rgba(255, 218, 35, 0)',
        borderColor: '#303030',
        data:[]
    },
    {
		label: '% Collected of Monthly Target',
		stack: "0",
		borderWidth: 1,
		backgroundColor: '<?php echo $percent_color; ?>',
		borderColor: '<?php echo $color; ?>',
		data:[]
	},
    {
		label: '% Forecasted of Monthly Target',
		stack: "0",
		borderWidth: 1,
		backgroundColor: '#7a7a7a',
		borderColor: '<?php echo $color; ?>',
		data:[]
	}

]
};

var barChartData_fopt = {
			type: 'bar',
			data: barChartData_f,
			options: {
				plugin_attribute:0,
				responsive: true,
				legend: {
					display: true
				},
				title: {
					display: false
				},
				legend:{
					labels:{
						fontSize:16
					}
				},
				scales: {
				   xAxes: [{
                        stacked: true,
						ticks: {
							fontSize: 12,
							fontStyle:'bold',
							fontColor:'<?php echo $color; ?>'
						}
				  }],
				  yAxes: [{
                        stacked: true,
						display: true,
						ticks: {
							fontSize: 20,
							fontStyle:'bold',
                            callback: function(value, index, values) {
                    if (Math.floor(value) === value) {
                        return value;
                    }
                }
						}
				  }]
				}
			}
};

var barChartData_gopt = {
			type: 'bar',
			data: barChartData_g,
			options: {
				plugin_attribute:0,
				responsive: true,
				legend: {
					display: true
				},
				title: {
					display: false
				},
				legend:{
					labels:{
						fontSize:16
					}
				},
				scales: {
				   xAxes: [{
						ticks: {
							fontSize: 12,
							fontStyle:'bold',
							fontColor:'<?php echo $color; ?>'
						}
				  }],
				  yAxes: [{
						display: true,
						ticks: {
							type:"%",
							fontSize: 20,
							fontStyle:'bold',
                            callback: function(value, index, values) {
                    if (Math.floor(value) === value) {
                        return value;
                    }
                }
						}
				  }]
				}
			}
};


function update_scren_14(the_id){
	$.ajax({
			url: '/admin/wallboard/apitest/'+the_id, // point to server-side PHP script
			dataType: 'json',  // what to expect back from the PHP script, if anything
			cache: true,
			contentType: 'json',
			processData: true,
		}).done(function(res){
            console.log(res);

			// Update values in the bottom table
			myBar_f.data.labels = res.chart_f.names;
			myBar_f.data.datasets[0].data = res.chart_f.line;
			myBar_f.data.datasets[1].data = res.chart_f.bar;
            myBar_f.data.datasets[2].data = res.chart_f.forecast_cash_f;
			// myBar_f.options.scales.yAxes[0].ticks.max = ((Math.max.apply(null, res.chart_f.line)) + (2000 - ((Math.max.apply(null, res.chart_f.line)) % 2000)));
			// myBar_f.options.scales.yAxes[0].ticks.max = (Math.max.apply(null, res.chart_f.forecast_cash_f) + Math.max.apply(null, res.chart_f.forecast_cash_f)*0.1);
			$(".percentage").html('');
			$(".percentage").append("<li style = 'font-size:20px'>"+ res.chart_g.names[0] +"</li>"+
										 "<li style = 'font-size:20px'>"+ res.chart_g.names[1] +"</li>"+
										 "<li style = 'font-size:20px'>"+ res.chart_g.names[2] +"</li>"+
										 "<li style = 'font-size:20px'>"+ res.chart_g.names[3] +"</li>"+
										 "<li style = 'font-size:20px'>"+ res.chart_g.names[4] +"</li>");
		  $(".cash").html('');
			$(".cash").append("<li style = 'font-size:20px'>"+ res.chart_topcash.names[0] +"</li>"+
										 "<li style = 'font-size:20px'>"+ res.chart_topcash.names[1] +"</li>"+
										 "<li style = 'font-size:20px'>"+ res.chart_topcash.names[2] +"</li>"+
										 "<li style = 'font-size:20px'>"+ res.chart_topcash.names[3] +"</li>"+
										 "<li style = 'font-size:20px'>"+ res.chart_topcash.names[4] +"</li>");

			myBar_f.update();



			// Update values in the top table
			myBar_g.data.labels = res.chart_g.names;
			if(res.chart_g.line[0] != "0.0"){
				myBar_g.data.datasets[0].data = res.chart_g.line;
			}
			myBar_g.data.datasets[2].data = res.chart_g.bar;
			myBar_g.data.datasets[3].data = res.chart_g.forecast;

			myBar_g.data.datasets[1].data = res.chart_g.forecast_phasing;


			// if the maximum % to target is below 100% then set 100% as the Y-limit, otherwise set it to the next highest 10
			// if(Math.max.apply(null, res.chart_g.bar) > 100){
			// myBar_g.options.scales.yAxes[0].ticks.max = ((Math.max.apply(null, res.chart_g.bar)) + (50 - ((Math.max.apply(null, res.chart_g.bar)) % 10)));
			// myBar_g.options.scales.yAxes[0].ticks.max = (Math.max.apply(null, res.chart_g.forecast) + Math.max.apply(null, res.chart_g.forecast)*0.1);
			// }else{
			// 	myBar_g.options.scales.yAxes[0].ticks.max = 100;
			// }


			myBar_g.update();


		});
}




</script>


<div class="container-fluid">
	<div class="row">

			<div class="col-md-9 mt-3 mb-0">
				<h5 class="header-bar bg-crsdblue text-white" style="margin-right:-400px;"><span>CRS</span> <?php echo $this->scr->more_info; ?> <span class="screen14figure_test float-right" ></span> </h5>
				<br>

				<div class = "row">
				<canvas height="600" width="1800" id="canvas_g" style="padding-left:50px"></canvas>
				</div>

				<div class = "row">
				<canvas height="600" width="1800" id="canvas_f" style="padding-left:50px"></canvas>
				</div>
			</div>

			<div class="col-md-3 mt-3 mb-0" style="padding-top:75px;">

				<div class="row row_data">
						<div class="col-md-12">
							<div class="card card-blue-white mt-0">
								<h5 class="card-header" style="font-size:16px; background-color:#00b7c6;">Top 5 % to target</h5><div class="card-body p-0" style="border-radius:6px">
									<ol class="percentage" style="padding-top:10px; font-weight:bold;">
									</ol>
								</div>
							</div>
						</div>
				</div>

				<div class="row row_data">
						<div class="col-md-12">
							<div class="card card-blue-white mt-0">
								<h5 class="card-header" style="font-size:16px; background-color:#00b7c6;">Top 5 £ collected</h5><div class="card-body p-0" style="border-radius:6px">
									<ol class="cash" style="padding-top:10px; font-weight:bold;">
									</ol>
								</div>
							</div>
						</div>
				</div>



			</div>


	</div>
</div>
