<!--
Code for Complaints section
-->

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-md-6">
      <div class="card transparent text-white no-overlap mt-3" style="height:350px;">
        <h5 class="card-headedfr borderbottom mt-0 no-overlap" style="padding:15px;">Complaints</h5>
        <div class="row">
          <div class="col-md-6">
            <p class= "pl-3"> Total Number of Complaints Logged MTD</p>
          </div>
          <div class="col-md-2">
            <p class= "pl-3"> <?php echo count($this->type); ?> </p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <p class= "pl-3"> Total Number of EOD's Logged MTD</p>
          </div>
          <div class="col-md-2">
            <p class= "pl-3"> <?php echo count($this->type1); ?> </p>
          </div>
        </div>
            <div class="card-body p-2">
            <table class="table m-0" style="table-layout: fixed;">

  <thead>
    <tr>
      <th></th>
      <th> > 5 </th>
      <th> < 2 </th>
      <th>Overdue</th>
    </tr>
  </thead>

<tbody class="update_incalldata transparent white-text">
    <tr>
      <th rowspan="1">Acknowledgement</th>

        </tr>
          <tr>
            <th rowspan="1">Investigation 4 Weeks</th>
          </tr>

      <tr>
      <th rowspan="1">Investigation 8 Weeks</th>
      </tr>

      <tr>
      <th rowspan="1">Under FOS Investigation</th>
      </tr>

</tbody>
</table>
</div>
</div>
</div>


<!--
Code for QA section
-->

<div class="col-xs-12 col-md-6">
  <div class="card transparent text-white no-overlap mt-3" style="height:350px;">
      <h5 class="card-headedfr borderbottom mt-0 no-overlap" style="padding:15px;">QA</h5>
    <div class="card-body p-2">
      <table class="table m-0"  style="table-layout: fixed;">
        <thead>
          <tr>
            <th></th>
            <th> month </th>
            <th> month </th>
            <th> month </th>
          </tr>
        </thead>


      <tbody class="update_incalldata transparent white-text">
          <tr>
            <th rowspan="1">Target</th>
              </tr>

                <tr>
                  <th rowspan="1">Completed</th>
                </tr>

            <tr>
            <th rowspan="1">Remaining</th>
            </tr>

            <tr>
            <th rowspan="1">Average Score</th>
            </tr>

      </tbody>
      </table>
      </div>
      </div>
      </div>

      <!--
      Code for Audits section
      -->


      <div class="col-xs-12 col-md-6">
        <div class="card transparent text-white no-overlap mt-3" style="height:350px;">
            <h5 class="card-headedfr borderbottom mt-0 no-overlap" style="padding:15px;">Audits</h5>
            <div class="card-body p-2">
              <table class="table m-0"  style="table-layout: fixed;">
                <thead>
                  <tr>
                    <th></th>
                    <th> month </th>
                    <th> month </th>
                    <th> month </th>
                  </tr>
                </thead>


              <tbody class="update_incalldata transparent white-text">
                  <tr>
                    <th rowspan="1">Audits Due</th>
                      </tr>

                        <tr>
                          <th rowspan="1">Ongoing</th>
                        </tr>

                    <tr>
                    <th rowspan="1">Finalising</th>
                    </tr>

                    <tr>
                    <th rowspan="1">Not Completed Score</th>
                    </tr>

                    <tr>
                    <th rowspan="1"> % of Red Audits </th>
                    </tr>

                    <tr>
                    <th rowspan="1"> Overdue Audit Actions </th>

                        <th></th>
                        <th> > 1 month </th>
                      </tr>



              </tbody>
              </table>
              </div>
              </div>
              </div>


      <!--
      Code for SAR section
      -->


      <div class="col-xs-12 col-md-6">
        <div class="card transparent text-white no-overlap mt-3" style="height:350px;">
            <h5 class="card-headedfr borderbottom mt-0 no-overlap" style="padding:15px;">SAR</h5>
            <div class="row">
              <div class="col-md-6">
                <p class= "pl-3"> Total Number Received MTD</p>
              </div>
              <div class="col-md-2">

              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <p class= "pl-3"> Completed MTD</p>
              </div>
              <div class="col-md-2">

              </div>
            </div>
          <div class="card-body p-2">
            <table class="table m-0"  style="table-layout: fixed;">
              <thead>
                <tr>
                  <th></th>
                  <th> > 5 </th>
                  <th> < 2 </th>
                  <th>Overdue</th>
                </tr>
              </thead>



            </table>
            </div>
            </div>
            </div>
