<?php 
$this->form->setAction('admin/wallboard/');
echo $this->form->renderForm();
echo $this->form->renderForm(false);
//echo $this->form->renderForm(false); ?>


<div id="field_include_group" class="form-group row"><div class="col-md-3">
	<?php echo $this->form->group->getLabel(); ?>
</div><div class="col-md-9 hide_label">
	<?php echo $this->form->getElement('group');?>
</div></div>


<div class="form-group row">
	<div class="col-sm-12">
		<?php echo $this->form->submit; ?>
	</div>
</div>
<?php 

?>