<?php  $this->pageTitle = 'Edit Client '; ?>

<?php echo $this->render('users/createclientuser.phtml'); ?>

  <script>    
                            
                ;(function($){
                
                    $(document).ready(function(){
                        
                         var clientCodes = '';
                         $('#field_client input:checked').each(function(index, item) {
                            clientCodes += $(this).parent().text()+',';
                        });
                           $('#tags').val(clientCodes);
                          
                    });
          
                })(jQuery);
                
 </script>   
